---
abstract: 'Multiple HTTP requests with Coro'
author:
  - 'Fuji, Goro (gfx) E<lt>gfuji@cpan.orgE<gt>'
build_requires: {}
configure_requires:
  Module::Build: 0.40
dynamic_config: 0
generated_by: 'Module::Build version 0.4003, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: FurlX-Coro
no_index:
  directory:
    - example
    - inc
    - t
    - xt
provides:
  FurlX::Coro:
    file: lib/FurlX/Coro.pm
    version: 1.00
  FurlX::Coro::HTTP:
    file: lib/FurlX/Coro/HTTP.pm
    version: 0
requires:
  perl: 5.008001
resources:
  license: http://dev.perl.org/licenses/
version: 1.00
